name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          filename: "stable.zip"
          # Remove .gitignore and .gitattributes files from the archive
          exclusions: "*.git* *.github*"
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "stable.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
